/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package kafka.txn.issue.demo;

import org.junit.jupiter.api.Test;

class AppTest {
    @Test void appHasAGreeting() {
        System.out.println("Oops no tests yet");
    }
}
